" -- PATHOGEN --
call pathogen#infect()
call pathogen#helptags()

" -- COLOR SCHEME --
"
set term=builtin_ansi
set t_Co=256
syntax on
colorscheme halloween_dark

" -- PLUGINS START --
"
" GitGutter
let g:gitgutter_sign_column_always = 1
highlight clear SignColumn
"let g:gitgutter_max_signs = 500  " default value
"let g:gitgutter_sign_added = 'xx'
"let g:gitgutter_sign_modified = 'yy'
"let g:gitgutter_sign_removed = 'zz'
"let g:gitgutter_sign_removed_first_line = '^^'
"let g:gitgutter_sign_modified_removed = 'ww'

" -- PLUGINS END --

" Show hidden characters
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<,nbsp:'
set list
set nu

" -- STATUS LINE --
" Left side
set laststatus=2
set statusline=%f  " Path to the file
set statusline+=%m "modified flag
set statusline+=%r "read only flag

" Right side
set statusline+=%= " Switch to the right side
set statusline+=\ %P "percent through file
set statusline+=/ " Separator
set statusline+=%L " Total lines
set statusline+=( " Separator
set statusline+=%c " Column
set statusline+=) " Separator

" Run on save
autocmd BufWritePost * GitGutter

" Enable Spell check
set spell spelllang=en_us

" Enable file type detection
filetype plugin on

" Language Config
autocmd BufRead,BufNewFile *.go set tabstop=4 softtabstop=4 shiftwidth=4 noexpandtab
let g:go_fmt_command = "goimports"
autocmd BufRead,BufNewFile *.md set tabstop=2 softtabstop=2 shiftwidth=2 noexpandtab
autocmd BufRead,BufNewFile *.c set tabstop=2 softtabstop=2 shiftwidth=2 noexpandtab


