" Version 1.0.0
" Author: Richard Hawkins
" URL: https://github.com/hurricanerix/hfor

" -- PATHOGEN --
call pathogen#infect()
call pathogen#helptags()

" -- PLUGINS START --
"
" GitGutter
let g:gitgutter_sign_column_always = 1
highlight clear SignColumn
"let g:gitgutter_max_signs = 500  " default value
"let g:gitgutter_sign_added = 'xx'
"let g:gitgutter_sign_modified = 'yy'
"let g:gitgutter_sign_removed = 'zz'
"let g:gitgutter_sign_removed_first_line = '^^'
"let g:gitgutter_sign_modified_removed = 'ww'

" -- PLUGINS END --

" -- COLOR SCHEME --
set term=builtin_ansi
set t_Co=8
syntax on
set background=dark
colorscheme blue
highlight SignColumn	ctermfg=Blue	ctermbg=DarkBlue
highlight SpecialKey	ctermfg=Blue	ctermbg=DarkBlue
highlight NonText	ctermfg=Blue	ctermbg=DarkBlue

" Show hidden characters
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<,nbsp:'
set list
set nu

" -- STATUS LINE --
" Left side
set laststatus=2
set statusline=%f  " Path to the file
set statusline+=%m "modified flag
set statusline+=%r "read only flag

" Right side
set statusline+=%= " Switch to the right side
set statusline+=\ %P "percent through file
set statusline+=/ " Separator
set statusline+=%L " Total lines
set statusline+=( " Separator
set statusline+=%c " Column
set statusline+=) " Separator

" Run on save
autocmd BufWritePost * GitGutter

" Enable Spell check
set spell spelllang=en_us
highlight	clear SpellBad
highlight	SpellBad cterm=underline ctermfg=Red

" Enable file type detection
filetype plugin on

" Go Config
"autocmd FileType go autocmd BufWritePre <buffer> Fmt
autocmd BufRead,BufNewFile *.go set tabstop=4 softtabstop=4 shiftwidth=4 noexpandtab
autocmd BufRead,BufNewFile *.c set tabstop=2 softtabstop=2 shiftwidth=2 noexpandtab
let g:go_fmt_command = "goimports"

" Python config
"if exists('+colorcolumn')
"  hi ColorColumn guibg=#000000 ctermbg=0
"  set colorcolumn=80
"endif

