#!/usr/bin/env bash

DEV=$1
if [ -n "$DEV" ]; then
	DEV="--dev"
fi

OS=`uname -a`

# OS specific things
if [[ "$OS" == *"Darwin"* ]]; then
	OS='macOS'
elif [[ "$OS" == *"Ubuntu"* ]]; then
	OS='Ubuntu'
	sudo apt-get -y install git zsh vim curl wget python
	sudo update-alternatives --set editor `which vim.basic`
else
	echo "Unsupported OS: $OS"
	exit 1
fi

if [ -z "$DEV" ]; then
	git clone git@github.com:hurricanerix/hfor.git $HOME/.hfor
fi

cd $HOME/.hfor
python tools/install.py $DEV $OS
